[package]
name = "utilitycss-compiler"
description = "Runtime-independent compiler facade for utilitycss."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
utilitycss-css-ir = { version = "0.1.0", path = "../utilitycss-css-ir" }
utilitycss-diagnostics = { version = "0.1.0", path = "../utilitycss-diagnostics" }
utilitycss-scanner = { version = "0.1.0", path = "../utilitycss-scanner" }
utilitycss-span = { version = "0.1.0", path = "../utilitycss-span" }
utilitycss-syntax = { version = "0.1.0", path = "../utilitycss-syntax" }
utilitycss-theme = { version = "0.1.0", path = "../utilitycss-theme" }
utilitycss-utilities = { version = "0.1.0", path = "../utilitycss-utilities" }
utilitycss-variants = { version = "0.1.0", path = "../utilitycss-variants" }

[lints]
workspace = true
