/** The generated WASM compiler constructor surface. */
export interface WasmCompilerConstructor {
  new (
    pretty?: boolean | null,
    configSource?: string | null,
    browserTarget?: string | null
  ): WasmCompiler;
}

/** The generated WASM compiler methods consumed by this wrapper. */
export interface WasmCompiler {
  updateSource(id: string, content: string, path?: string | null): void;
  updateSourceWithCandidates(
    id: string,
    content: string,
    path: string | null | undefined,
    candidates: readonly CandidateInput[]
  ): void;
  extractCandidates(content: string, path?: string | null): CandidateInput[];
  removeSource(id: string): boolean;
  build(): BuildResult;
  /**
   * Explains one candidate. Returns the stable JSON introspection payload,
   * using the same encoding as the N-API adapter; hosts `JSON.parse` it.
   */
  explain(candidate: string): string;
  /**
   * Validates one candidate. Returns the stable JSON validation payload,
   * using the same encoding as the N-API adapter; hosts `JSON.parse` it.
   */
  validate(candidate: string): string;
  capabilities(): string;
  transformStylesheet(id: string, content: string, path?: string | null): StylesheetResult;
  /** Releases the underlying WASM allocation; generated by wasm-bindgen. */
  free(): void;
}

/** Work counters returned by a WASM compiler build. */
export interface CompileStats {
  readonly sourcesScanned: number;
  readonly bytesScanned: number;
  readonly candidatesFound: number;
  readonly uniqueCandidates: number;
  readonly candidatesParsed: number;
  readonly cacheHits: number;
  readonly rulesGenerated: number;
  readonly rulesRemoved: number;
}

/** A normalized result from one WASM compiler build. */
export interface BuildResult {
  readonly css: string;
  readonly diagnostics: readonly Diagnostic[];
  readonly stats: CompileStats;
}

/** A host-selected candidate span accepted by the WASM compiler. */
export interface CandidateInput {
  readonly raw: string;
  readonly start: number;
  readonly end: number;
  readonly extractionMode?: "text" | "static" | "ast" | "hybrid";
}

/** A normalized stylesheet transformation result from WASM. */
export interface StylesheetResult {
  readonly css: string;
  readonly diagnostics: readonly Diagnostic[];
}

/** A diagnostic returned by the WASM stylesheet transformer. */
export interface Diagnostic {
  readonly severity?: "error" | "warning" | "note" | "help";
  readonly code: string;
  readonly message: string;
  readonly source?: string;
  readonly start?: number;
  readonly end?: number;
  readonly help?: string;
  readonly explanation?: string;
  readonly suggestions?: readonly string[];
}

/** A generated WASM module containing the compiler constructor. */
export interface WasmModule {
  readonly WasmCompiler: WasmCompilerConstructor;
}

/** Creates a compiler wrapper from an initialized wasm-bindgen module. */
export function createWasmCompiler(
  module: WasmModule,
  pretty: boolean | null = false,
  configSource?: string | null,
  browserTarget?: string | null
): WasmCompiler {
  if (typeof module.WasmCompiler !== "function") {
    throw new Error("WASM module does not export WasmCompiler");
  }
  return new module.WasmCompiler(pretty, configSource ?? undefined, browserTarget ?? undefined);
}
