import { Badge } from "./Badge.tsx";
import { Button } from "./Button.tsx";

export function TableSection({ onNew }: { onNew: () => void }) {
  return (
    <div className="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b-1 border-gray-200 p-5"><div><h3 className="text-lg font-semibold text-gray-900">Recent deployments</h3><p className="mt-1 text-sm text-gray-500">A small responsive data table.</p></div><Button variant="outline" onClick={onNew}>New deployment</Button></div>
      <div className="overflow-auto"><table className="w-full table-auto text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wider text-gray-500"><tr><th className="px-5 py-3 font-semibold">Project</th><th className="px-5 py-3 font-semibold">Branch</th><th className="px-5 py-3 font-semibold">Status</th><th className="px-5 py-3 font-semibold">Updated</th><th className="px-5 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody><tr className="border-b-1 border-gray-100"><td className="whitespace-nowrap px-5 py-4 font-semibold text-gray-900">utilitycss-site</td><td className="px-5 py-4 font-mono text-xs text-gray-500">main</td><td className="px-5 py-4"><Badge variant="success">Ready</Badge></td><td className="px-5 py-4 text-gray-500">2 min ago</td><td className="px-5 py-4 text-right"><Button className="button-small" variant="ghost">View</Button></td></tr><tr className="border-b-1 border-gray-100"><td className="whitespace-nowrap px-5 py-4 font-semibold text-gray-900">docs-preview</td><td className="px-5 py-4 font-mono text-xs text-gray-500">feat/docs</td><td className="px-5 py-4"><Badge variant="warning">Building</Badge></td><td className="px-5 py-4 text-gray-500">8 min ago</td><td className="px-5 py-4 text-right"><Button className="button-small" variant="ghost">View</Button></td></tr><tr><td className="whitespace-nowrap px-5 py-4 font-semibold text-gray-900">component-kit</td><td className="px-5 py-4 font-mono text-xs text-gray-500">fix/buttons</td><td className="px-5 py-4"><Badge variant="danger">Failed</Badge></td><td className="px-5 py-4 text-gray-500">21 min ago</td><td className="px-5 py-4 text-right"><Button className="button-small" variant="ghost">View</Button></td></tr></tbody></table></div>
    </div>
  );
}
