[package]
name = "utilitycss-scanner"
description = "Fast, runtime-independent utility candidate scanner for utilitycss."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
utilitycss-span = { version = "0.1.0", path = "../utilitycss-span" }

[dev-dependencies]
proptest = "=1.11.0"

[lints]
workspace = true
