[package]
name = "utilitycss-lsp"
description = "Language Server Protocol adapter for utilitycss diagnostics and completions."
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tokio = { version = "=1.53.1", features = ["io-std", "macros", "rt-multi-thread"] }
tower-lsp = "=0.20.0"
utilitycss-compiler = { path = "../utilitycss-compiler" }
utilitycss-extractor = { path = "../utilitycss-extractor" }
utilitycss-span = { path = "../utilitycss-span" }
utilitycss-swc = { path = "../utilitycss-swc" }

[lints]
workspace = true
