[package]
name = "utilitycss-cli"
description = "Native command-line interface for utilitycss."
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
notify = "8.2.0"
walkdir = "2.5.0"
utilitycss-css-ir = { path = "../utilitycss-css-ir" }
utilitycss-compiler = { path = "../utilitycss-compiler" }
utilitycss-config = { path = "../utilitycss-config" }
utilitycss-span = { path = "../utilitycss-span" }

[lints]
workspace = true
