[package]
name = "utilitycss-utilities"
description = "Registry and semantic lowering for the initial utilitycss utility set."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
utilitycss-css-ir = { version = "0.1.0", path = "../utilitycss-css-ir" }
utilitycss-diagnostics = { version = "0.1.0", path = "../utilitycss-diagnostics" }
utilitycss-span = { version = "0.1.0", path = "../utilitycss-span" }
utilitycss-syntax = { version = "0.1.0", path = "../utilitycss-syntax" }
utilitycss-theme = { version = "0.1.0", path = "../utilitycss-theme" }

[lints]
workspace = true
