[package]
name = "utilitycss-wasm"
description = "Thin WebAssembly binding for the utilitycss compiler facade."
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
utilitycss-compiler = { path = "../utilitycss-compiler" }
utilitycss-css-ir = { path = "../utilitycss-css-ir" }
utilitycss-span = { path = "../utilitycss-span" }
wasm-bindgen = "0.2"

[lints]
workspace = true
