[package]
name = "utilitycss-wasm"
description = "Thin WebAssembly binding for the utilitycss compiler facade."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
utilitycss-compiler = { version = "0.1.0", path = "../utilitycss-compiler" }
utilitycss-css-ir = { version = "0.1.0", path = "../utilitycss-css-ir" }
utilitycss-scanner = { version = "0.1.0", path = "../utilitycss-scanner" }
utilitycss-stylesheet = { version = "0.1.0", path = "../utilitycss-stylesheet" }
utilitycss-span = { version = "0.1.0", path = "../utilitycss-span" }
wasm-bindgen = "0.2"

[lints]
workspace = true
