/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A reusable JavaScript-facing compiler instance. */
export declare class Compiler {
  /** Creates a compiler with optional readable output, declarative config, and browser target. */
  constructor(pretty?: boolean | undefined | null, configSource?: string | undefined | null, browserTarget?: string | undefined | null)
  /** Inserts or replaces one source unit. */
  updateSource(id: string, content: string, path?: string | undefined | null, candidates?: Array<JsCandidate> | undefined | null): void
  /** Extracts static class candidates using SWC or the selected framework adapter. */
  extractCandidates(content: string, path?: string | undefined | null): Array<JsCandidate>
  /** Removes one source unit and returns whether it existed. */
  removeSource(id: string): boolean
  /** Builds the current sources and returns CSS, diagnostics, and counters. */
  build(): JsBuildResult
  /** Explains one candidate and returns the stable JSON introspection payload. */
  explain(candidate: string): string
  /** Validates one candidate and returns the stable JSON validation payload. */
  validate(candidate: string): string
  /** Returns the active machine-readable capability manifest as JSON. */
  capabilities(): string
  /** Transforms authored CSS and resolves explicit `@apply` directives. */
  transformStylesheet(id: string, content: string, path?: string | undefined | null): JsStylesheetResult
}

/** A compiler build result returned to JavaScript. */
export interface JsBuildResult {
  /** Serialized CSS output. */
  css: string
  /** Structured compiler diagnostics. */
  diagnostics: Array<JsDiagnostic>
  /** Work counters for this build. */
  stats: JsStats
}

/** A statically extracted candidate accepted by the batched source update API. */
export interface JsCandidate {
  /** Candidate text, which MUST match the source span exactly. */
  raw: string
  /** Inclusive start byte offset. */
  start: number
  /** Exclusive end byte offset. */
  end: number
  /** Extraction mode that produced this candidate. */
  extractionMode?: string
}

/** A diagnostic returned across the N-API boundary. */
export interface JsDiagnostic {
  /** Stable severity name. */
  severity: string
  /** Stable diagnostic code. */
  code: string
  /** Human-readable diagnostic message. */
  message: string
  /** Optional source identity. */
  source?: string
  /** Optional start byte offset. */
  start?: number
  /** Optional exclusive end byte offset. */
  end?: number
  /** Optional actionable help text. */
  help?: string
  /** Optional longer explanation for IDE and agent clients. */
  explanation?: string
  /** Deterministic replacement suggestions. */
  suggestions: Array<string>
}

/** Build counters returned across the N-API boundary. */
export interface JsStats {
  /** Number of source units scanned on updates. */
  sourcesScanned: number
  /** Number of source bytes scanned on updates. */
  bytesScanned: number
  /** Number of candidate occurrences found on updates. */
  candidatesFound: number
  /** Number of unique active candidates. */
  uniqueCandidates: number
  /** Number of candidates parsed on this build. */
  candidatesParsed: number
  /** Number of active candidates served from cache. */
  cacheHits: number
  /** Number of active rules emitted. */
  rulesGenerated: number
  /** Number of rules removed from active references. */
  rulesRemoved: number
}

/** A stylesheet transformation result returned across the N-API boundary. */
export interface JsStylesheetResult {
  /** Transformed authored CSS. */
  css: string
  /** Structured stylesheet and composition diagnostics. */
  diagnostics: Array<JsDiagnostic>
}
